"""
agents.py

This module defines the agent nodes (Writer and Critic) used in the LangGraph workflow.
Instead of hardcoded responses, agents now read from an active scenario loaded from
test_scenarios.json, enabling multi-scenario testing across different domains.
"""
from langchain_core.messages import HumanMessage, AIMessage


def writer_node(state: dict) -> dict:
    """
    The Writer agent responsible for generating and updating the draft report.

    In a production system, this node invokes a Large Language Model (LLM)
    to draft content based on the user's request and historical critique.
    Here, we simulate the writer using pre-written drafts from the active scenario
    to demonstrate the semantic halting problem.

    The writer follows a clear progression:
        - Loops 0 to N-1:  uses the scripted drafts from the scenario.
        - Loop N onwards:  enters deadlock by alternating between two near-identical
                           variants, simulating an agent that has stopped adding value.

    Args:
        state (dict): The current state of the LangGraph workflow, containing:
            - scenario (dict):   The currently active test scenario from test_scenarios.json.
            - history (list):    Previous drafts and feedback.
            - loop_count (int):  The number of iterations completed so far.

    Returns:
        dict: A dictionary containing the updated 'current_draft' string.
    """
    scenario = state.get("scenario", {})
    loop_count = state.get("loop_count", 0)
    scripted_drafts = scenario.get("drafts", [])
    deadlock_variants = scenario.get("deadlock_variants", ["Variant A.", "Variant B."])

    if loop_count < len(scripted_drafts):
        # Use the scripted draft for this loop iteration
        draft = scripted_drafts[loop_count]
    else:
        # Enter deadlock: trivially alternate between near-identical wordings
        choice = deadlock_variants[loop_count % len(deadlock_variants)]
        draft = f"Draft {loop_count + 1}: {choice}"

    print(f"\n[Writer] Generated Draft {loop_count + 1}: ...{draft[-60:]}")
    return {"current_draft": draft}


def critic_node(state: dict) -> dict:
    """
    The Critic agent responsible for reviewing the draft and providing feedback.

    This node simulates an LLM-based critique driven by the active scenario's
    feedback list. Constructive feedback is given for the first few rounds; after
    that, the critic enters a pedantic loop to demonstrate how semantic deadlock
    occurs when no new information is added.

    Args:
        state (dict): The current state of the LangGraph workflow, containing:
            - scenario (dict):     The currently active test scenario.
            - current_draft (str): The latest draft generated by the writer.
            - loop_count (int):    The current iteration number.
            - history (list):      Previous interactions.

    Returns:
        dict: A dictionary containing the updated 'history' and incremented 'loop_count'.
    """
    scenario = state.get("scenario", {})
    draft = state.get("current_draft", "")
    loop_count = state.get("loop_count", 0)
    scripted_feedbacks = scenario.get("feedbacks", [])

    if loop_count < len(scripted_feedbacks):
        # Use the scripted, constructive feedback
        feedback = scripted_feedbacks[loop_count]
    else:
        # Deadlock: loop over the last two feedbacks endlessly
        looping_feedbacks = scripted_feedbacks[-2:] if len(scripted_feedbacks) >= 2 else scripted_feedbacks
        feedback = looping_feedbacks[loop_count % len(looping_feedbacks)]

    print(f"[Critic] Feedback: {feedback}")

    history = state.get("history", [])
    history.append({"draft": draft, "feedback": feedback})

    return {
        "history": history,
        "loop_count": loop_count + 1
    }
